version: "3.9"
services:
  movies:
    build: .
    ports:
    - 80:80
    env_file:
    - .env
    volumes:
    - /mnt/movies_db:/app/db
  auth:
    build: ./auth
    ports:
    - 3000:3000
    env_file:
    - .env