openapi: 3.0.0
info:
  title: Movies API
  description: Simple API to create and get movie records by authenticated users
  version: 1.0.0
servers:
  - url: http://localhost/
    description: Local development server
paths:
  /movies:
    get:
      summary: Return all the movies created by user.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movies'
        '400':
          description: Bad request error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Error'
    post:
      description: Post new movie to user's account
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  description: Name of a movie to be added
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDetails'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        Error:
          type: string
    Movies:
      type: array
      items:
        type: object
        properties:
          User:
            type: string
          Genre:
            type: string
          Title:
            type: string
          Director:
            type: string
          Released:
            type: string
          Timestamp:
            type: string
        xml:
          name: Tag
    MovieDetails:
      type: object
      properties:
        Genre:
          type: string
        Title:
          type: string
        Director:
          type: string
        Released:
          type: string
      xml:
        name: Tag
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
